### ISSUE TITLE
[Task] Feat: 게시글 상세보기 컴포넌트 구현

### ISSUE THREAD

**Issue by KimJaewon3** [codestates/FaCo#34]
### TODO

1. [x]  게시판에서 해당 게시글을 눌렀을때 그에 맞는 게시글이 보여져야함 
2. [x]  로그인한 유저의 게시글이라면 수정이 가능해야함 (버튼이 생성됨)
3. [x]  좋아요를 누를수 있어야함
4. [x]  상세보기와 게시글 목록을 함께 볼 수 있어야함
