### ISSUE TITLE
[Task] img view 컴포넌트 구현 (여러개의 이미지를 넘겨가며 볼 수 있음)

### ISSUE THREAD

**Issue by KimJaewon3** [codestates/FaCo#48]
### TODO

1. [x]  이미지의 개수만큼 보여줘야함
2. [x]  버튼을 누르면 전, 후의 이미지를 볼 수 있어야함
3. [x]  하단에 전체 이미지에 대한 작은 미리보기가 있어야함
4. [x]  작은 미리보기 클릭시 해당 이미지가 메인에 보여져야함
